### ISSUE TITLE
Internal Error. Details are available in Magento log file. Report ID: webapi-5959d1b2a569d

### ISSUE THREAD

**Issue by ratnesh-kadam** [yireo-training/magento2-example-address-field-note#1]
After filling all the details on checkout clicked on next...and it gives an warning "Internal Error. Details are available in Magento log file. Report ID: webapi-5959d1b2a569d". can you please help to resolve this issue.?

[2017-07-03 04:58:09] main.CRITICAL: LogtcException: Property "Note" does not have corresponding setter in class "Magento\Quote\Api\Data\AddressExtensionInterface". in /home/ratnesh/lampstack/apache2/htdocs/test-yireo/vendor/magento/framework/Reflection/NameFinder.php:100
Stack trace:
#0 /home/ratnesh/lampstack/apache2/htdocs/test-yireo/vendor/magento/framework/Reflection/NameFinder.php(59): Magento\Framework\Reflection\NameFinder->findAccessorMethodName(Object(Zend\Code\Reflection\ClassReflection), 'Note', 'getNote', 'isNote')
#1 /home/ratnesh/lampstack/apache2/htdocs/test-yireo/vendor/magento/framework/Webapi/ServiceInputProcessor.php(158): Magento\Framework\Reflection\NameFinder->getGetterMethodName(Object(Zend\Code\Reflection\ClassReflection), 'Note')
#2 /home/ratnesh/lampstack/apache2/htdocs/test-yireo/vendor/magento/framework/Webapi/ServiceInputProcessor.php(322): Magento\Framework\Webapi\ServiceInputProcessor->_createFromArray('\\Magento\\Quote\\...', Array)
#3 /home/ratnesh/lampstack/apache2/htdocs/test-yireo/vendor/magento/framework/Webapi/ServiceInputProcessor.php(175): Magento\Framework\Webapi\ServiceInputProcessor->convertValue(Array, '\\Magento\\Quote\\...')
#4 /home/ratnesh/lampstack/apache2/htdocs/test-yireo/vendor/magento/framework/Webapi/ServiceInputProcessor.php(322): Magento\Framework\Webapi\ServiceInputProcessor->_createFromArray('\\Magento\\Quote\\...', Array)
#5 /home/ratnesh/lampstack/apache2/htdocs/test-yireo/vendor/magento/framework/Webapi/ServiceInputProcessor.php(175): Magento\Framework\Webapi\ServiceInputProcessor->convertValue(Array, '\\Magento\\Quote\\...')
#6 /home/ratnesh/lampstack/apache2/htdocs/test-yireo/vendor/magento/framework/Webapi/ServiceInputProcessor.php(322): Magento\Framework\Webapi\ServiceInputProcessor->_createFromArray('Magento\\Checkou...', Array)
#7 /home/ratnesh/lampstack/apache2/htdocs/test-yireo/vendor/magento/framework/Webapi/ServiceInputProcessor.php(119): Magento\Framework\Webapi\ServiceInputProcessor->convertValue(Array, 'Magento\\Checkou...')
#8 /home/ratnesh/lampstack/apache2/htdocs/test-yireo/vendor/magento/module-webapi/Controller/Rest/InputParamsResolver.php(101): Magento\Framework\Webapi\ServiceInputProcessor->process('Magento\\Checkou...', 'saveAddressInfo...', Array)
#9 /home/ratnesh/lampstack/apache2/htdocs/test-yireo/vendor/magento/module-webapi/Controller/Rest.php(299): Magento\Webapi\Controller\Rest\InputParamsResolver->resolve()
#10 /home/ratnesh/lampstack/apache2/htdocs/test-yireo/vendor/magento/module-webapi/Controller/Rest.php(216): Magento\Webapi\Controller\Rest->processApiRequest()
#11 /home/ratnesh/lampstack/apache2/htdocs/test-yireo/var/generation/Magento/Webapi/Controller/Rest/Interceptor.php(24): Magento\Webapi\Controller\Rest->dispatch(Object(Magento\Framework\App\Request\Http))
#12 /home/ratnesh/lampstack/apache2/htdocs/test-yireo/vendor/magento/framework/App/Http.php(135): Magento\Webapi\Controller\Rest\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#13 /home/ratnesh/lampstack/apache2/htdocs/test-yireo/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#14 /home/ratnesh/lampstack/apache2/htdocs/test-yireo/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#15 {main}

Next Exception: Report ID: webapi-5959cee12028d; Message: Property "Note" does not have corresponding setter in class "Magento\Quote\Api\Data\AddressExtensionInterface". in /home/ratnesh/lampstack/apache2/htdocs/test-yireo/vendor/magento/framework/Webapi/ErrorProcessor.php:195
Stack trace:
#0 /home/ratnesh/lampstack/apache2/htdocs/test-yireo/vendor/magento/framework/Webapi/ErrorProcessor.php(139): Magento\Framework\Webapi\ErrorProcessor->_critical(Object(LogicException))
#1 /home/ratnesh/lampstack/apache2/htdocs/test-yireo/vendor/magento/module-webapi/Controller/Rest.php(219): Magento\Framework\Webapi\ErrorProcessor->maskException(Object(LogicException))
#2 /home/ratnesh/lampstack/apache2/htdocs/test-yireo/var/generation/Magento/Webapi/Controller/Rest/Interceptor.php(24): Magento\Webapi\Controller\Rest->dispatch(Object(Magento\Framework\App\Request\Http))
#3 /home/ratnesh/lampstack/apache2/htdocs/test-yireo/vendor/magento/framework/App/Http.php(135): Magento\Webapi\Controller\Rest\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#4 /home/ratnesh/lampstack/apache2/htdocs/test-yireo/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#5 /home/ratnesh/lampstack/apache2/htdocs/test-yireo/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#6 {main} [] []

**Comment by jissereitsma** [comment]
Thanks for reporting. Note that this extension is not meant for production anyway, so you as a developer are in control and in charge of fixing this. The code is also not meant to give unpaid to others. Instead, it is my business to give paid trainings to other developers. And instead of keeping the code for those trainings to myself and those trainees, it is shared with others. It is not meant as a way for others to get third party code. In short: It is actual open source. Whatever you want to do with the source, is up to you. I will see if I have time somewhere in the future to see what is the problem.
